global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

scrape_configs:
  - job_name: 'pinger'
    static_configs:
      - targets: ['pinger:3000']
    metrics_path: '/metrics'
    scrape_interval: 5s
    scrape_timeout: 3s

  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
